apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argo-test
  name: argo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-test
    spec:
      containers:
      - image: nginx:alpine-perl
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
