apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: argo-test
  name: argo-test
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argo-test
  type: ClusterIP
status:
  loadBalancer: {}
